name: bike_go
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  image_picker: ^2.0.0  # Updated to a newer version
  path_provider: ^2.1.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding_map.png
    - assets/images/onboarding_scan.png
    - assets/images/onboarding_ride.png
    - assets/images/onboarding_park.png 
